In [1]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [12]:
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.models import Sequential
from keras.layers import Embedding,Dense,Input
tokenizer = Tokenizer()

In [4]:
tokenizer.fit_on_texts(docs)

In [5]:
len(tokenizer.word_index)

17

In [6]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [7]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [16]:
model = Sequential()

model.add(Input(shape=(5,)))

model.add(Embedding(
    input_dim=18,
    output_dim=2
))

model.summary()

# vocab length = 17, output_dim = dimension of dense vector we want.
# input_dim = len(tokenizer.word_index) + 1 = vocab + 1

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 5, 2)           │            36 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 36 (144.00 B)

 Trainable params: 36 (144.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.compile('adam','accuracy')

In [18]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
[[[-0.01813645  0.04937246]
  [ 0.00464379 -0.04634302]
  [ 0.03602816  0.01955283]
  [ 0.03602816  0.01955283]
  [ 0.03602816  0.01955283]]

 [[ 0.00464379 -0.04634302]
  [ 0.00464379 -0.04634302]
  [ 0.03602816  0.01955283]
  [ 0.03602816  0.01955283]
  [ 0.03602816  0.01955283]]

 [[-0.02439805  0.01472567]
  [-0.02439805  0.01472567]
  [-0.03789085  0.0198748 ]
  [ 0.03602816  0.01955283]
  [ 0.03602816  0.01955283]]

 [[-0.02246099  0.04733587]
  [ 0.01454811  0.02785927]
  [-0.02246099  0.04733587]
  [ 0.00464379 -0.04634302]
  [-0.02246099  0.04733587]]

 [[ 0.02897217  0.03332385]
  [-0.02489636  0.02481784]
  [ 0.0406475   0.02812502]
  [ 0.04953197 -0.00756919]
  [ 0.03602816  0.01955283]]

 [[-0.00418869 -0.03763131]
  [-0.00418869 -0.03763131]
  [ 0.03602816  0.01955283]
  [ 0.03602816  0.01955283]
  [ 0.03602816  0.01955283]]

 [[ 0.04447961 -0.0298831 ]
  [ 0.04447961 -0.0298831 ]
  [ 0.03602816  0.01955283]
  [ 0.03602816  0.01955283

# Sentiment Analysis

In [20]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [21]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
# Method to find vocab_size
vocab_size = max(max(sequence) for sequence in X_train) + 1 # +1 because embedding indices start at 0.
vocab_size

np.int32(88586)

In [22]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [23]:
X_train.shape

(25000, 50)

In [39]:
model = Sequential()

model.add(Input(shape=(50,)))
model.add(Embedding(input_dim=vocab_size, output_dim=2)) # Embedding layer, limiting input_dim to 10000
model.add(SimpleRNN(32,return_sequences=False)) # RNN layer
model.add(Dense(1, activation='sigmoid')) # output layer

model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)         │ (None, 50, 2)          │       177,172 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_4 (SimpleRNN)        │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 178,325 (696.58 KB)

 Trainable params: 178,325 (696.58 KB)

 Non-trainable params: 0 (0.00 B)

In [40]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 17ms/step - acc: 0.6378 - loss: 0.6041 - val_acc: 0.8018 - val_loss: 0.4464
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - acc: 0.8447 - loss: 0.3623 - val_acc: 0.8070 - val_loss: 0.4549
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 21s 16ms/step - acc: 0.9044 - loss: 0.2476 - val_acc: 0.8077 - val_loss: 0.4659
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 25s 22ms/step - acc: 0.9338 - loss: 0.1793 - val_acc: 0.7993 - val_loss: 0.4749
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - acc: 0.9524 - loss: 0.1391 - val_acc: 0.7852 - val_loss: 0.6057
